// deployooor_gui/src/routes/generateKeyStore/+page.svelte
<script lang="ts">
  import { invoke } from "@tauri-apps/api/tauri";
  $: name = "";
  $: password = "";
  const handleKeyGen = () => {
    invoke("create_key", {
      path: "./",
      nickname: name,
      password: password,
    });
  };
</script>

<form class="w-1/3 m-auto mt-24">
  <label class="label mt-4">
    <span>Name</span>
    <input bind:value={name} class="input" type="text" />
  </label>
  <label class="label mt-4">
    <span>Password</span>
    <input bind:value={password} class="input" type="password" />
  </label>

  <button
    on:click={() => handleKeyGen()}
    type="button"
    class="btn rounded-lg bg-slate-950 mt-4">Submit</button
  >
</form>

// src/pages/generate-keystore.tsx
import { invoke } from '@tauri-apps/api/tauri';
import { useState } from 'react';
import { useStatus } from '../hooks'

export const GenerateKeystorePage = () => {
  const [password, setPassword] = useState('');
  const [name, setName] = useState('');

  const [status, setStatus] = useStatus('idle');

  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    setStatus('loading')
    try {
      e.preventDefault();
  
      const res = await invoke('create_key', {
        path: `./`,
        password,
        nickname: name,
      });

      console.log(res);
    } catch (e) {
      console.log(e)
      setStatus('error')
    } finally {
      setStatus('success')
    }
  };

  return (
    <form className='flex flex-col gap-4' onSubmit={onSubmit}>
      <div className='form-control'>
        <label htmlFor='password' className='label'>
          Password
        </label>
        <input
          className='input input-bordered'
          type='password'
          id='password'
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />
      </div>

      <div className='form-control'>
        <label htmlFor='name' className='label'>
          Name
        </label>
        <input
          className='input input-bordered'
          type='text'
          id='name'
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
      </div>

      <button className='btn btn-primary' type='submit'>
        Generate Keystore
      </button>

      <pre>
        <code>
          {JSON.stringify(status, null, 2)}
        </code>
      </pre>
    </form>
  );
};
